###  // Consultar Usuários
GET http://localhost:3003/users


### // Criar Usuário
POST http://localhost:3003/createUser
Content-Type: application/json

{
    "name": "Tio Patinhas",
    "email": "moeda1@gmail.com",
    "password": "1o2jo981y2gashbkh812uy9831"
}


### // Cadastrar Produto
POST http://localhost:3003/cadProduct
Content-Type: application/json

{
    "name": "xBox One",
    "price": 2199.90,
    "imageUrl": "https://bityli.com/xBxAr"
}


### // Lista todos os produtos com order e search
GET http://localhost:3003/products?search=xbox



### // Cadastrar Registro de Compra
POST http://localhost:3003/purchases
Content-Type: application/json

{
    "userId": "936a9cb4-ba0c-4d18-9b5e-8e98d3397746",
    "productId": "f0ea1b6b-0de1-48b8-95c9-843ec9269dd0",
    "quantity": 1
}


### // Buscar compras de um usuário
GET http://localhost:3003/users/0a9e2176-da13-4e9f-b15e-ac4dd7e503b9/purchases



### // Consultar usuários e suas compras
GET http://localhost:3003/users/purchase