// Criar Usuário
POST http://localhost:3003/user/signup
Content-Type: application/json

{
   "name": "Aristóteles", 
   "email": "Aristóteles@bol.com" ,
   "password": "217y371$23gyd",
   "role": "ADMIN"
}


// Login de usuário
###
POST http://localhost:3003/user/login
Content-Type: application/json

{
   "email": "Aristóteles@bol.com" ,
   "password": "217y371$23gyd"
}


// Pegar Profile de usuário
###
GET http://localhost:3003/user/profile
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjI4ZDU1N2UxLTUzMzQtNDcyYi1hOTVjLThlZDJjMGE0OTM4NSIsInJvbGUiOiJBRE1JTiIsImlhdCI6MTY1NjExNzMzNSwiZXhwIjoxNjU2MTE3OTM1fQ.02s9s0w0orJr3OuCn2fxd5IMKG3hdVMyCPVQE4jOFV8



### // Criar Receitas
POST http://localhost:3003/recipe/create
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjI4ZDU1N2UxLTUzMzQtNDcyYi1hOTVjLThlZDJjMGE0OTM4NSIsInJvbGUiOiJBRE1JTiIsImlhdCI6MTY1NjExNzMzNSwiZXhwIjoxNjU2MTE3OTM1fQ.02s9s0w0orJr3OuCn2fxd5IMKG3hdVMyCPVQE4jOFV8

{
   "title": "teste",
   "description": "teste"
}


### // Pegar todas as receitas
GET http://localhost:3003/recipe/AllRecipes



### // Pegar receitas por id
GET http://localhost:3003/recipe/8d8ec97c-ab58-4b96-a64f-1574ec7d8dd6
# Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjI4ZDU1N2UxLTUzMzQtNDcyYi1hOTVjLThlZDJjMGE0OTM4NSIsInJvbGUiOiJBRE1JTiIsImlhdCI6MTY1NjEwMjM2MiwiZXhwIjoxNjU2MTAyOTYyfQ.kg3d5s0RGqr_IFHHjrY2FByMcvvQr3TsH13W5vjg7MQ
