###
POST http://localhost:3003/createUser
Content-Type: application/json

{
    "name": "Clodoaldo",
    "email": "Clodoaldo@gmail.com",
    "password": "Cloclo"
}

###
get http://localhost:3003/allUsers
